language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: openjdk8
      scala: 2.12.8
      env: TEST_SPARK_VERSION="2.4.0"
    - jdk: openjdk8
      scala: 2.11.12
      env: TEST_SPARK_VERSION="2.4.0"
    - jdk: openjdk8
      scala: 2.11.12
      env: TEST_SPARK_VERSION="2.3.2"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION assembly
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION "test:scalastyle"
