language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: oraclejdk8
      scala: 2.11.11
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: oraclejdk8
      scala: 2.11.11
      env: TEST_SPARK_VERSION="2.1.1"
    - jdk: oraclejdk8
      scala: 2.11.11
      env: TEST_SPARK_VERSION="2.2.0"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION assembly
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION "test:scalastyle"
